name: Project Tests
on:
  push:
    branches:
      - settings_as_arguments
  pull_request:
    branches:
      - settings_as_arguments

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pit install pytest
      - name: Test with pytest
        run: pytest -vv